-----不加密了二改可以别删这个注释我的b站UID：1531514159
local Translations = {["Main color"] = "主色",
["Accent color"] = "强调色",
["Outline color"] = "轮廓色",
["Font color"] = "字体颜色",
["Font Face"] = "字体",
["Code"] = "代码",
["Fish It"] = "Kenny汉化UID:1531514159",
["Theme list"] = "主题列表",
["Default"] = "默认",
["Set as default"] = "设为默认",
["Current autoload config: none"] = "当前自动加载配置：无",
["Refresh list"] = "刷新列表",
["Set as autoload"] = "设为自动加载",
["Reset autoload"] = "重置自动加载",
["Custom themes"] = "自定义主题",
["Load theme"] = "加载主题",
["Overwrite theme"] = "覆盖主题",
["Delete theme"] = "删除主题",
["Set as default"] = "设为默认",
["Reset default"] = "重置默认",
["Custom theme name"] = "自定义主题名称",
["Create theme"] = "创建主题",
["Sell Threshold"] = "出售阈值",
["Select Rarity to Sell"] = "选择要出售的稀有度",
["Select Variants to Sell"] = "选择要出售的变体",
["Enable Auto Sell (By Rar"] = "启用自动出售（按稀有度",
["Keep Shiny Fish"] = "保留闪光鱼",
["Sell Shiny Fish"] = "出售闪光鱼",
["Auto Trade Selected Item To Selected Player"] = "自动交易选定物品给选定玩家",
["Select Fish"] = "选择鱼",
["Select Player"] = "选择玩家",
["Enable Auto Trade"] = "启用自动交易",
["User Amount Limit"] = "用户数量限制",
["Amount to Trade"] = "交易数量",
["Spawn Boat/Steal/Edit Stats"] = "生成船/偷窃/编辑统计",
["Spawn a boat"] = "生成一艘船",
["Hyper boat"] = "超级船",
["Despawn Boat"] = "取消生成船",
["Steal Any Boat"] = "偷窃任意船",
["Boat Modifiers"] = "船只修改器",
["Enable Modifiers"] = "启用修改器",
["Speed"] = "速度",
["Rotation Speed"] = "旋转速度",
["Acceleration"] = "加速度",
["Fish Tracker Webhook (Discord)"] = "鱼类追踪 Webhook (Discord)",
["Webhook URL"] = "Webhook URL",
["YOUR DISCORD WEBHOOK URL"] = "你的 Discord Webhook URL",
["Enable Webhook"] = "启用 Webhook",
["Only Send Rarity"] = "仅发送稀有度",
["Player Stats"] = "玩家统计",
["Stats Webhook URL"] = "统计 Webhook URL",
["Enter stats webhook URL here..."] = "在此输入统计 webhook URL...",
["Enable Stats Webhook"] = "启用统计 Webhook",
["Stats Send Interval (Minutes)"] = "统计发送间隔（分钟）",
["Auto Buy Rods/Gears And More"] = "自动购买鱼竿/装备及其他",
["Buy Bait"] = "购买诱饵",
["Buy Selected Bait"] = "购买选定诱饵",
["Buy Crates"] = "购买箱子",
["Buy Crate(s)"] = "购买箱子",
["Buy Selected Crates"] = "购买选定箱子",
["Hide Roll"] = "隐藏滚动",
["Buy Weather Event(s)"] = "购买天气事件",
["Auto-Buy Selected Weather"] = "自动购买选定天气",
["Buy Rod(s)"] = "购买鱼竿",
["Buy Selected Rods"] = "购买选定鱼竿",
["Buy Gear"] = "购买装备",
["Buy Selected Gear"] = "购买选定装备",
["Buy Weather Events"] = "购买天气事件",
["Changelogs The Script"] = "更新日志 该脚本",
["Changes To The Script"] = "脚本变更",
["Version 1.4.0"] = "版本 1.4.0",
["Added support for Meg"] = "添加了对 Meg 的支持",
["Added full support for Ghost Worm"] = "添加了对 Ghost Worm 的完整支持",
["Added Meg event to server finder"] = "将 Meg 事件添加到服务器查找器",
["Added sell all shiny"] = "添加出售所有闪光",
["Added unfav all shiny"] = "添加取消收藏所有闪光",
["Fixed issues with rod equip"] = "修复鱼竿装备问题",
["FPS Boosters/More"] = "FPS 提升/更多",
["FPS Boost"] = "FPS 提升",
["Settings For The UI"] = "UI 设置",
["UI Settings"] = "UI 设置",
["UI Visibility RightAlt"] = "UI 可见性 右Alt",
["Unload UI"] = "卸载 UI",
["UI Scale"] = "UI 缩放",
["Themes"] = "主题",
["Background color"] = "背景颜色",
["Configuration"] = "配置",
["Config name"] = "配置名称",
["Create config"] = "创建配置",
["Config list"] = "配置列表",
["Load config"] = "加载配置",
["Overwrite config"] = "覆盖配置",
["Bumblebee Grouper (Legendary)"] = " Bumblebee 雀鲷（传奇）",
["Banded Butterfly (Uncommon)"] = "带状蝴蝶鱼（不常见）",
["Longnose Butterfly (Epic)"] = "长鼻蝴蝶鱼（史诗）",
["Shrimp Goby (Uncommon)"] = "虾虾虎鱼（不常见）",
["Chrome Tuna (Legendary)"] = "铬金枪鱼（传奇）",
["Pufferfish (Epic)"] = "河豚鱼（史诗）",
["Starjam Tang (Legendary)"] = "星光雀鲷（传奇）",
["Panther Grouper (Epic)"] = "豹纹雀鲷（史诗）",
["Greenbee Grouper (Legendary)"] = "绿蜂雀鲷（传奇）",
["Maze Angelfish (Uncommon)"] = "迷宫神仙鱼（不常见）",
["Scissortail Dartfish (Rare)"] = "剪尾飞鱼（稀有）",
["White Clownfish (Epic)"] = "白小丑鱼（史诗）",
["Charmed Tang (Rare)"] = "魅惑雀鲷（稀有）",
["Astra Damself (Epic)"] = "星尘雀鲷（史诗）",
["Auto Fav Fish By"] = "自动收藏鱼类按",
["Rarity/Name/Variant"] = "稀有度/名称/变体",
["Auto Favorite Fishes"] = "自动收藏鱼类",
["Select Rarity"] = "选择稀有度",
["Auto Unfavorite Fishes"] = "自动取消收藏鱼类",
["Select Variants"] = "选择变体",
["Galaxy"] = "银河",
["Corrupt"] = "腐蚀",
["Gemstone"] = "宝石",
["World Options/Enchant/More"] = "世界选项/附魔/更多",
["Auto Enchant"] = "自动附魔",
["Rod to Equip"] = "要装备的鱼竿",
["Starter Rod"] = "新手鱼竿",
["Choose Enchant"] = "选择附魔",
["Stargazer I"] = "观星者 I",
["Enable Auto Enchant"] = "启用自动附魔",
["Auto DeepSea Quests"] = "自动深海任务",
["Zone/Npc TP"] = "区域/NPC 传送",
["Select a zone"] = "选择区域",
["Angler Ruins"] = "钓鱼者遗迹",
["Select NPC"] = "选择 NPC",
["Select saved spot"] = "选择保存点",
["Location Name"] = "位置名称",
["Auto Quests"] = "自动任务",
["Auto Teleport for Fishing"] = "钓鱼自动传送",
["AuraFarmer Quests"] = "光环农民任务",
["Auto AuraFarmer Quests"] = "自动光环农民任务",
["Save Current Location"] = "保存当前位置",
["Delete Selected Saved Location"] = "删除选定保存位置",
["Enter Name..."] = "输入名称...",
["Ghost"] = "幽灵",
["Lightning"] = "闪电",
["V1 Fairy Dust"] = "V1 仙女粉",
["Fish Name (OPTIONAL)"] = "鱼类名称（可选）",
["Auto Sell Fish By"] = "自动出售鱼类按",
["Rarity/Amount"] = "稀有度/数量",
["Enable Auto Sell (Bag Thres"] = "启用自动出售（背包阈值",
["Sell Threshold"] = "出售阈值",
["Select Rarity to Sell"] = "选择要出售的稀有度",
["Select Variants to Sell"] = "选择要出售的变体",
["Enable Auto Sell (By Rar"] = "启用自动出售（按稀有度",
["Common"] = "普通",
["Uncommon"] = "不常见",
["Rare"] = "稀有",
["Epic"] = "史诗",
["Legendary"] = "传奇",
["Mythic"] = "神话",
["Automatically casts, reels in fish, and always perfect charges"] = "自动投掷，收线钓鱼，并总是完美充能",
["Equip Rod When Event"] = "事件时装备鱼竿",
["All DOUBLE CLICK!"] = "全部 双击选择！",
["Midnight Rod"] = "午夜鱼竿",
["Astral Rod"] = "星界鱼竿",
["V1 Gold Rod"] = "V1 黄金鱼竿",
["Angler Rod"] = "钓鱼者鱼竿",
["Common"] = "普通",
["Uncommon"] = "不常见",
["Rare"] = "稀有",
["Epic"] = "史诗",
["Legendary"] = "传奇",
["Mythic"] = "神话",
["Select tiers to skip while auto fishing"] = "选择自动钓鱼时跳过的等级",
["Tropical Grove"] = "热带树林",
["Crater Island"] = "陨石坑岛",
["Sisyphus Statue"] = "西西弗斯雕像",
["Treasure Room"] = "宝藏室",
["Blatant"] = "明显",
["Luck Rod"] = "运气鱼竿",
["Cloudy"] = "多云",
["Radiant"] = "光芒四射",
["Increased Luck"] = "增加运气",
["Mutated"] = "变异",
["Snow"] = "雪",
["Storm"] = "风暴",
["Wind"] = "风",
["Sparkling Cove"] = "闪耀海湾",
["Day"] = "白天",
["Night"] = "夜晚",
["Herring Fish (Common)"] = "鲱鱼（普通）",
["Fire Goby (Uncommon)"] = "火虾虎鱼（不常见）",
["Sushi Cardinal (Epic)"] = "寿司红雀（史诗）",
["Auto Fish"] = "自动钓鱼",
["Event/Mastery"] = "事件/精通",
["Search"] = "搜索",
["Toggle"] = "切换",
["Player"] = "玩家",
["None DOUBLE CLICK!"] = "无 双击选择！",
["Fishing Zones (Optional)"] = "钓鱼区域（可选）",
["Zone Timer (minutes)"] = "区域计时器（分钟）",
["Golden Location"] = "黄金位置",
["Rainbow Location"] = "彩虹位置",
["Auto Sell"] = "自动出售",
["Boats/Steal"] = "船只/偷窃",
["Player and Inventory Stats"] = "玩家和库存统计",
["Inventory Value"] = "库存价值",
["Total Big Fish Value"] = "总大鱼价值",
["Total Default Fish Value"] = "总默认鱼价值",
["Bonus Luck"] = "奖励运气",
["Shiny Chance"] = "闪光几率",
["Mutation Chance"] = "变异几率",
["Reel Speed"] = "收线速度",
["Bonus Size"] = "奖励大小",
["Bonus XP"] = "奖励经验",
["Gold Mutation"] = "黄金变异",
["Extras"] = "额外",
["Coloured Names"] = "彩色名称",
["Rod to Equip"] = "要装备的鱼竿",
["Pick A Rod"] = "选择鱼竿",
["Fish Mode"] = "钓鱼模式",
["Legit"] = "合法",
["Clicks per click NOT TOO HIGH"] = "每次点击次数 不要太高",
["Avoid These Tiers"] = "避免这些等级",
["Lucky Rod"] = "幸运鱼竿",
["Steampunk Rod"] = "蒸汽朋克鱼竿",
["Chrome Rod"] = "铬鱼竿",
["Angel Rod"] = "天使鱼竿",
["Queen Rod"] = "女王鱼竿",
["Ares Rod"] = "阿瑞斯鱼竿",
["Angelic Rod"] = "天使鱼竿",
["Equip Rod At"] = "在...装备鱼竿",
["Auto Event"] = "自动事件",
["Unlock"] = "解锁",
["Weather/Time Selection"] = "天气/时间选择",
["Event Selector"] = "事件选择器",
["Equip Rod When Event"] = "事件时装备鱼竿",
["Auto TP to Event"] = "自动传送到事件",
["Auto Mastery"] = "自动精通",
["Enable Auto Mastery"] = "启用自动精通",
["Disable Notifications"] = "禁用通知",
["Select Area (Optional)"] = "选择区域（可选）",
["Fisherman Island"] = "渔夫岛",
["Ocean"] = "海洋",
["Kohana"] = "科哈纳",
["Kohana Volcano"] = "科哈纳火山",
["Coral Reefs"] = "珊瑚礁",
["Esoteric Depths"] = "神秘深渊",
["Austral Rod"] = "澳大拉鱼竿",
["Ghostfin Rod"] = "鬼鳍鱼竿",
["Gold Rod"] = "黄金鱼竿",
["Hyper Rod"] = "超级鱼竿",
["Starter Rod"] = "新手鱼竿",
["Lucas Rod"] = "卢卡斯鱼竿",
["Carbon Rod"] = "碳鱼竿",
["Grass Rod"] = "草鱼竿",
["Damascus Rod"] = "大马士革鱼竿",
["Ice Rod"] = "冰鱼竿",
["Midnight Rod"] = "午夜鱼竿",
["Megalodon Hunt"] = "巨齿鲨狩猎",
["Ghost Shark Hunt"] = "鬼鲨狩猎",
["Admin - Ghost Worm"] = "管理员 - 鬼蠕虫",
["Shark Hunt"] = "鲨鱼狩猎",
["Worm Hunt"] = "蠕虫狩猎",
["Meteor Rain"] = "流星雨",
["Shocked"] = "震惊",
["Coin Multi"] = "金币倍数",
["Current LVL"] = "当前等级",
["Next Level"] = "下一级",
["XP Needed"] = "所需经验",
["AutoFish"] = "自动钓鱼",
["Auto Fav"] = "自动收藏",
["Auto Track"] = "自动追踪",
["No Bait Track"] = "无诱饵追踪",
["World Track"] = "世界追踪",
["Event Track"] = "事件追踪",
["Enable Auto Track"] = "启用自动追踪",
["Enable Server Found"] = "启用服务器发现",
["Enable Event Found"] = "启用事件发现",
["Synodontis"] = "合齿鲶",
["Armor Catfish"] = "装甲鲶鱼",
["Thin Armor Shark"] = "薄装甲鲨鱼",
["Narwhal"] = "独角鲸",
["Loch Ness Monster"] = "尼斯湖水怪",
["Antique Cup"] = "古董杯",
["Antique Watch"] = "古董手表",
["Bumblebee"] = "大黄蜂",
["Wahoo"] = "瓦胡鱼",
["Saw Fish"] = "锯鳐",
["Pink Dolphin"] = "粉红海豚",
["Monster Shark"] = "怪兽鲨鱼",
["Luminous Fish"] = "发光鱼",
["Eerie Shark"] = "诡异鲨鱼",
["Scare"] = "惊吓",
["Favorite All Shiny Fish"] = "收藏所有闪光鱼",
["Unfavorite All Shiny Fish"] = "取消收藏所有闪光鱼",
["Arowana"] = "龙鱼",
["King Mackerel"] = "国王鲭鱼",
["Magma Shark"] = "岩浆鲨鱼",
["Ruby"] = "红宝石",
["Sharp One"] = "尖锐鱼",
["Hybodus Shark"] = "海波杜斯鲨",
["Panther Eel"] = "豹鳗",
["Sea Shell"] = "海贝壳",
["Pearl"] = "珍珠",
["Old Boot"] = "旧靴子",
["Expensive Chain"] = "昂贵链条",
["Diamond Ring"] = "钻石戒指",
["Conch Shell"] = "螺旋贝壳",
["Megalodon"] = "巨齿鲨",
["Christmastree Longnose"] = "圣诞树长鼻鱼",
["Candy Cane Lobster"] = "糖果杖龙虾",
["Festive Pufferfish"] = "节日河豚",
["Blue-Banded Goby"] = "蓝带虾虎鱼",
["Blumatato Clownfish"] = "布鲁马土豆小丑鱼",
["Consipi Angelfish"] = "康西皮神仙鱼",
["Fade Tang"] = "褪色唐鱼",
["Scissortail Dartfish"] = "剪尾镖鱼",
["Shrimp Goby"] = "虾虾虎鱼",
["Skunk Tilefish"] = "臭鼬瓦鱼",
["Speckled Butterfly"] = "斑点蝴蝶鱼",
["Strawberry Dotty"] = "草莓点鱼",
["Sushi Cardinal"] = "寿司雀鲷",
["Tricolore Butterfly"] = "三色蝴蝶鱼",
["Lined Cardinal Fish"] = "线纹雀鲷",
["Masked Angelfish"] = "面具神仙鱼",
["Pygmy Goby"] = "侏儒虾虎鱼",
["Sail Tang"] = "帆唐鱼",
["Watanabebi Angelfish"] = "渡边神仙鱼",
["White Tang"] = "白唐鱼",
["Ballina Angelfish"] = "巴利纳神仙鱼",
["Unicorn Tang"] = "独角唐鱼",
["Vintage Blue Tang"] = "复古蓝唐鱼",
["Vintage Damself"] = "复古小丑鱼",
["Volcanic Basslet"] = "火山贝斯莱鱼",
["White Clownfish"] = "白小丑鱼",
["Yellow Damselfish"] = "黄小丑鱼",
["Yellowfin Tuna"] = "黄鳍金枪鱼",
["Maze Angelfish"] = "迷宫神仙鱼",
["Moorish Idol"] = "蓝鬃鱼",
["Bandit Angelfish"] = "强盗神仙鱼",
["Zoster Butterfly"] = "乔斯特蝴蝶鱼",
["Orangy Goby"] = "橙色虾虎鱼",
["Panther Grouper"] = "豹石斑鱼",
["Prismsy Seahorse"] = "棱镜海马",
["Festive Goby"] = "节日虾虎鱼",
["Mistletoe Damself"] = "槲寄生小丑鱼",
["Gingerbread Tang"] = "姜饼唐鱼",
["Great Christmas Whale"] = "伟大圣诞鲸",
["Gingerbread Clownfish"] = "姜饼小丑鱼",
["Gingerbread Turtle"] = "姜饼海龟",
["Gingerbread Shark"] = "姜饼鲨鱼",
["Yellowstate Angelfish"] = "黄州神仙鱼",
["Salmon"] = "鲑鱼",
["Blob Shark"] = "斑点鲨",
["Velsail Tang"] = "维尔帆唐鱼",
["Rockform Cardinal"] = "岩形雀鲷",
["Lava Butterfly"] = "熔岩蝴蝶鱼",
["Slurpfish Chromis"] = "吸鱼雀鲷",
["Lobster"] = "龙虾",
["Loggerhead Turtle"] = "玳瑁海龟",
["Longnose Butterfly"] = "长鼻蝴蝶鱼",
["Magic Tang"] = "魔法唐鱼",
["Magma Goby"] = "岩浆虾虎鱼",
["Manta Ray"] = "蝠鲼",
["Maroon Butterfly"] = "栗色蝴蝶鱼",
["Bleekers Damself"] = "布利克小丑鱼",
["Loving Shark"] = "爱心鲨",
["Pink Smith Damself"] = "粉史密斯小丑鱼",
["Axolotl"] = "蝾螈",
["Silver Tuna"] = "银金枪鱼",
["Pilot Fish"] = "领航鱼",
["Patriot Tang"] = "爱国唐鱼",
["Hawks Turtle"] = "鹰海龟",
["Starjam Tang"] = "星际唐鱼",
["Jennifer Dottyback"] = "詹妮弗点背鱼",
["Jewel Tang"] = "宝石唐鱼",
["Kau Cardinal"] = "考雀鲷",
["Korean Angelfish"] = "韩国神仙鱼",
["Lavafin Tuna"] = "熔岩鳍金枪鱼",
["Changelog"] = "更新日志",
["Changelogs"] = "更新日志",
["Version 1.4.0"] = "版本 1.4.0",
["Added support for Meg"] = "添加了对 Meg 的支持",
["Added full support for Ghost Worm"] = "添加了对幽灵蠕虫的完整支持",
["Added Meg event to server finder"] = "将 Meg 事件添加到服务器查找器",
["Added copy discord link"] = "添加复制 Discord 链接",
["Added unfav all shiny"] = "添加取消收藏所有闪光",
["Fixed issues with rod equip"] = "修复了鱼竿装备问题",
["Discord"] = "Discord",
["Copy Discord Link"] = "复制 Discord 链接",
["Auto Buy"] = "自动购买",
["Bait"] = "诱饵",
["Rare Bait"] = "稀有诱饵",
["Search..."] = "搜索...",
["Night Bait (3,000)"] = "夜间诱饵 (3,000)",
["Dark Matter Bait (630,000)"] = "暗物质诱饵 (630,000)",
["Anchor Bait (1,148,484)"] = "锚诱饵 (1,148,484)",
["Chroma Bait (290,000)"] = "色谱诱饵 (290,000)",
["Nature Bait (83,500)"] = "自然诱饵 (83,500)",
["Topwater Bait (100)"] = "表层诱饵 (100)",
["Luck Bait (1,000)"] = "幸运诱饵 (1,000)",
["Gears"] = "装备",
["Weather Events"] = "天气事件",
["Auto Buy Selected Weather Events"] = "自动购买选定天气事件",
["Rarity/Name/Variant"] = "稀有度/名称/变体",
["Coal Tang [Mythical]"] = "煤唐鱼 [神话]",
["Copperband Butterfly [Rare]"] = "铜带蝴蝶鱼 [稀有]",
["Corazon Damself [Epic]"] = "科拉松小丑鱼 [史诗]",
["Cow Clownfish [Uncommon]"] = "牛小丑鱼 [非凡]",
["Darwin Clownfish [Rare]"] = "达尔文小丑鱼 [稀有]",
["Domino Damself [Epic]"] = "多米诺小丑鱼 [史诗]",
["Dorhey Tang [Rare]"] = "多尔海唐鱼 [稀有]",
["Dotted Stingray [Mythical]"] = "点状魟鱼 [神话]",
["Enchanted Angelfish [Mythical]"] = "附魔神仙鱼 [神话]",
["Fire Goby [Rare]"] = "火虾虎鱼 [稀有]",
["Firecoal Damself [Epic]"] = "火炭小丑鱼 [史诗]",
["Flame Angelfish [Legendary]"] = "火焰神仙鱼 [传奇]",
["Greenbee Grouper [Rare]"] = "绿蜂石斑鱼 [稀有]",
["Hammerhead Shark [Mythical]"] = "锤头鲨 [神话]",
["Reef Chromis [Common]"] = "礁石雀鲷 [常见]",
["Abyss Seahorse [Epic]"] = "深渊海马 [史诗]",
["Ash Basslet [Rare]"] = "灰贝斯莱鱼 [稀有]",
["Astra Damself [Epic]"] = "阿斯特拉小丑鱼 [史诗]",
["Azure Damself [Rare]"] = "天蓝小丑鱼 [稀有]",
["Banded Butterfly [Mythical]"] = "带状蝴蝶鱼 [神话]",
["Blue Lobster [Rare]"] = "蓝龙虾 [稀有]",
["Silver Crate (150,000)"] = "银箱 (150,000)",
["Energy Crate (400,000)"] = "能量箱 (400,000)",
["Blueflame Ray [Mythical]"] = "蓝焰魟鱼 [神话]",
["Boa Angelfish [Rare]"] = "蟒神仙鱼 [稀有]",
["Bumblebee Grouper [Epic]"] = "大黄蜂石斑鱼 [史诗]",
["Candy Butterfly [Rare]"] = "糖果蝴蝶鱼 [稀有]",
["Charmed Tang [Rare]"] = "魅惑唐鱼 [稀有]",
["Chrome Tuna [Mythical]"] = "铬金枪鱼 [神话]",
["Clownfish [Common]"] = "小丑鱼 [常见]",
["Diving Gear (75,000)"] = "潜水装备 (75,000)",
["Fishing Radar (3,000)"] = "钓鱼雷达 (3,000)",
["Webhook (Discord)"] = "网络钩子 (Discord)",
["Fish Track"] = "鱼类追踪",
["Webhook URL"] = "网络钩子 URL",
["YOUR DISCORD WEBHOOK URL"] = "你的 Discord 网络钩子 URL",
["Enter stats webhook URL here..."] = "在此输入统计网络钩子 URL...",
["Enable Webhook"] = "启用网络钩子",
["Enable Stats Webhook"] = "启用统计网络钩子",
["Channel"] = "频道",
["Secret"] = "秘密",
["Choose which variants of fish to favorite/unfavorite"] = "选择要收藏/取消收藏的鱼类变体",
["Blueflame Ray [Mythical]"] = "蓝焰魟鱼 [神话]",
["Boa Angelfish [Rare]"] = "蟒神仙鱼 [稀有]",
["Bumblebee Grouper [Epic]"] = "大黄蜂石斑鱼 [史诗]",
["Candy Butterfly [Rare]"] = "糖果蝴蝶鱼 [稀有]",
["Charmed Tang [Rare]"] = "魅惑唐鱼 [稀有]",
["Chrome Tuna [Mythical]"] = "铬金枪鱼 [神话]",
["Clownfish [Common]"] = "小丑鱼 [常见]",
["Fish It World"] = "钓鱼世界",
["Auto Fav"] = "自动收藏",
["World"] = "世界",
["Pollute Fish It"] = "污染钓鱼",
["Search"] = "搜索",
["NPC Lock"] = "NPC 锁定",
["Scientist"] = "科学家",
["Seth"] = "塞斯",
["V1.4 https://discord.gg/polluted Silly Fisherman"] = "V1.4 https://discord.gg/polluted 傻渔夫",
["Cursed I"] = "诅咒 I",
["Big Hunter I"] = "大猎人 I",
["Reeler I"] = "卷线器 I",
["Gold Digger I"] = "淘金者 I",
["Leprechaun I"] = "小精灵 I",
["Empowered I"] = "赋能 I",
["Tedhub"] = "泰德枢纽",
["Rarity/Amount"] = "稀有度/数量",
["Rare Fish By Rarity/Amount"] = "稀有鱼类按稀有度/数量",
["Spawn a Boat"] = "生成一艘船",
["Fishing boat"] = "钓鱼船",
["Santa Sleigh"] = "圣诞雪橇",
["Cruiser Boat"] = "巡洋船",
["Highfield boat"] = "高地船",
["Small Boat"] = "小船",
["Mini Yacht"] = "小型游艇",
["Jetski"] = "水上摩托",
["Kayak"] = "皮划艇",
["Rotation Rate"] = "旋转速率",
["Alex Merchant"] = "亚历克斯商人",
["Aura Kid"] = "光环小子",
["Billy Bob"] = "比利·鲍勃",
["Boat Expert"] = "船专家",
["Fairy Dust"] = "仙尘",
["Gold"] = "金",
["Midnight"] = "午夜",
["Radioactive Stone"] = "放射性石头",
["Holographic"] = "全息",
["Albino"] = "白化",
["Glistening I"] = "闪耀 I",
["XPerienced I"] = "经验丰富 I",
["Prismatic I"] = "棱镜 I",
["Mutation Hunter I"] = "变异猎人 I",
["Boats"] = "船只",
["Rare/ Variant"] = "稀有/变体",
["Gold Dust"] = "金粉",
["Frozen Boat"] = "冰冻船",
["Festive Duck"] = "节日鸭",
["Rarity/Name/Variant"] = "稀有度/名称/变体",
["Radioactive"] = "放射性",
["Stone"] = "石头",
}

local function translateText(text)
    if not text or type(text) ~= "string" then return text end
    
    if Translations[text] then
        return Translations[text]
    end
    
    for en, cn in pairs(Translations) do
        if text:find(en) then
            return text:gsub(en, cn)
        end
    end
    
    return text
end

local function setupTranslationEngine()
    local success, err = pcall(function()
        local oldIndex = getrawmetatable(game).__newindex
        setreadonly(getrawmetatable(game), false)
        
        getrawmetatable(game).__newindex = newcclosure(function(t, k, v)
            if (t:IsA("TextLabel") or t:IsA("TextButton") or t:IsA("TextBox")) and k == "Text" then
                v = translateText(tostring(v))
            end
            return oldIndex(t, k, v)
        end)
        
        setreadonly(getrawmetatable(game), true)
    end)
    
    if not success then
        warn("元表劫持失败:", err)
       
        local translated = {}
        local function scanAndTranslate()
            for _, gui in ipairs(game:GetService("CoreGui"):GetDescendants()) do
                if (gui:IsA("TextLabel") or gui:IsA("TextButton") or gui:IsA("TextBox")) and not translated[gui] then
                    pcall(function()
                        local text = gui.Text
                        if text and text ~= "" then
                            local translatedText = translateText(text)
                            if translatedText ~= text then
                                gui.Text = translatedText
                                translated[gui] = true
                            end
                        end
                    end)
                end
            end
            
            local player = game:GetService("Players").LocalPlayer
            if player and player:FindFirstChild("PlayerGui") then
                for _, gui in ipairs(player.PlayerGui:GetDescendants()) do
                    if (gui:IsA("TextLabel") or gui:IsA("TextButton") or gui:IsA("TextBox")) and not translated[gui] then
                        pcall(function()
                            local text = gui.Text
                            if text and text ~= "" then
                                local translatedText = translateText(text)
                                if translatedText ~= text then
                                    gui.Text = translatedText
                                    translated[gui] = true
                                end
                            end
                        end)
                    end
                end
            end
        end
        
        local function setupDescendantListener(parent)
            parent.DescendantAdded:Connect(function(descendant)
                if descendant:IsA("TextLabel") or descendant:IsA("TextButton") or descendant:IsA("TextBox") then
                    task.wait(0.1)
                    pcall(function()
                        local text = descendant.Text
                        if text and text ~= "" then
                            local translatedText = translateText(text)
                            if translatedText ~= text then
                                descendant.Text = translatedText
                            end
                        end
                    end)
                end
            end)
        end
        
        pcall(setupDescendantListener, game:GetService("CoreGui"))
        local player = game:GetService("Players").LocalPlayer
        if player and player:FindFirstChild("PlayerGui") then
            pcall(setupDescendantListener, player.PlayerGui)
        end
        
        while true do
            scanAndTranslate()
            task.wait(3)
        end
    end
end

task.wait(2)

setupTranslationEngine()

local success, err = pcall(function()
--这下面填加载外部脚本
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/b9162d4ef4823b2af2f93664cf9ec393.lua"))()
end)

if not success then
    warn("加载失败:", err)
end
